spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/<your-tenant-id>/v2.0
          client-id: <your-client-id>
logging:
  level:
    org.springframework: debug